import type { ItemDetail, Lang } from "../domain/types";
import { categoryNames, fmt, itemSubtypeNames, localizedSourceJobs, readableSourceText } from "../domain/display";
import { ItemTypeIcon, MonsterPortrait } from "./VisualIcons";

export default function ItemInfo({ item, lang, onMonster }: { item: ItemDetail; lang: Lang; onMonster: (monsterId: number) => void }) {
  const locale = lang === "de" ? "de-DE" : "en-US";
  const equipJobsLabel = localizedSourceJobs(item.equip_jobs, lang);
  const cardPrefixLabel = readableSourceText(item.card_prefix_name);
  const stat = (label: string, value: React.ReactNode) => <span><small>{label}</small><strong>{value}</strong></span>;
  return <div className="itemDetailBody">
    <div className="itemDetailIntro"><div className="itemDetailImage"><ItemTypeIcon itemId={item.item_id} category={item.category} subtype={item.subtype} name={item.name_en} /></div><div><small>#{item.item_id ?? "?"}{item.aegis_name ? ` · ${item.aegis_name}` : ""}</small><h3>{item.name_en}</h3><p>{categoryNames[item.category]?.[lang] || item.category} · {item.subtype ? itemSubtypeNames[item.subtype]?.[lang] || item.subtype : "—"}</p>{cardPrefixLabel && <em>{lang === "de" ? "Kartenpräfix" : "Card prefix"}: {cardPrefixLabel}</em>}</div></div>
    <div className="itemDetailStats">{stat("ATK", fmt(item.attack, lang))}{stat("MATK", fmt(item.magic_attack, lang))}{stat("DEF", fmt(item.defense, lang))}{stat("MDEF", fmt(item.magic_defense, lang))}{stat(lang === "de" ? "BENÖTIGTES LEVEL" : "REQUIRED LEVEL", fmt(item.required_level, lang))}{stat(lang === "de" ? "WAFFENLEVEL" : "WEAPON LEVEL", fmt(item.weapon_level, lang))}{stat(lang === "de" ? "KARTENSLOTS" : "CARD SLOTS", fmt(item.slots, lang))}{stat(lang === "de" ? "GEWICHT" : "WEIGHT", fmt(item.weight, lang))}{stat(lang === "de" ? "NPC-KAUFPREIS" : "NPC BUY PRICE", item.buy_price != null ? `${fmt(item.buy_price, lang)} z` : "—")}{stat(lang === "de" ? "NPC-VERKAUF" : "NPC SELL", item.sell_price != null ? `${fmt(item.sell_price, lang)} z` : "—")}{stat(lang === "de" ? "HANDELBAR" : "TRADEABLE", item.can_trade == null ? "—" : item.can_trade ? (lang === "de" ? "Ja" : "Yes") : (lang === "de" ? "Nein" : "No"))}{stat(lang === "de" ? "VERFEINERBAR" : "REFINABLE", item.refinable == null ? "—" : item.refinable ? (lang === "de" ? "Ja" : "Yes") : (lang === "de" ? "Nein" : "No"))}</div>
    {item.description && <div className="itemDescription"><h4>{lang === "de" ? "Beschreibung und Effekte" : "Description and effects"}</h4><p>{item.description}</p></div>}
    {equipJobsLabel && item.category !== "Card" && <p className="itemJobs"><b>{lang === "de" ? "Klassen laut Quelle" : "Classes according to source"}:</b> {equipJobsLabel}</p>}
    <div className="itemDroppers"><div className="itemDropperHead"><h4>{lang === "de" ? "Wird gedroppt von" : "Dropped by"}</h4><span>{item.dropped_by.length} {lang === "de" ? "Monster" : "monsters"}</span></div>{item.dropped_by.length ? item.dropped_by.map((monster) => <button key={`${item.source_slug}-${monster.monster_id}-${monster.name_en}`} disabled={monster.monster_id == null} onClick={() => monster.monster_id != null && onMonster(monster.monster_id)}><span className="itemDropperIdentity"><MonsterPortrait monsterId={monster.monster_id} name={monster.name_en} /><span><strong>{monster.name_en.replaceAll("_", " ")}</strong><small>{monster.monster_id != null ? `#${monster.monster_id}` : ""}{monster.level != null ? ` · Lv ${monster.level}` : ""}</small></span></span><span><small>{lang === "de" ? "DROPCHANCE" : "DROP RATE"}</small><strong>{monster.rate_percent != null ? `${monster.rate_percent.toLocaleString(locale, { maximumFractionDigits: 4 })}%` : monster.raw_rate && monster.raw_rate !== "???" ? String(monster.raw_rate) : "—"}</strong></span><em>{monster.monster_id != null ? (lang === "de" ? "Monster ansehen →" : "View monster →") : ""}</em></button>) : <p className="noDrops">{lang === "de" ? "Keine droppenden Monster in der Quelle hinterlegt. Das Item kann aus Shop, Quest, Box oder noch nicht veröffentlichtem Inhalt stammen." : "No dropping monsters are listed in the source. The item may come from a shop, quest, box, or unreleased content."}</p>}</div>
  </div>;
}
