import { useEffect, useMemo, useState } from 'react';
import type { Lang } from './domain/types';
import { api } from './services/api-client';
import './helpers.css';
import './skill-descriptions.css';
export type Skill = { k:string; n:string; b?:string; max:number; a:string; q:number; v:[string,number][]; st:Record<string,string>[] };
export type SkillData = {families:{erst:string;zweit:string[]}[]; skills:Record<string,Skill[]>; source:string};
const roles:Record<string,[string,string]>={Swordsman:['Physischer Nahkampf; Grundlage für Knight und Crusader.','Physical melee combat; foundation for Knight and Crusader.'],Mage:['Elementare Magie; Grundlage für Wizard und Sage.','Elemental magic; foundation for Wizard and Sage.'],Archer:['Fernkampf; Grundlage für Hunter, Bard und Dancer.','Ranged combat; foundation for Hunter, Bard and Dancer.'],Acolyte:['Heilung und Unterstützung; Grundlage für Priest und Monk.','Healing and support; foundation for Priest and Monk.'],Merchant:['Handel und Herstellung; Grundlage für Blacksmith und Alchemist.','Trading and crafting; foundation for Blacksmith and Alchemist.'],Thief:['Beweglicher Nahkampf; Grundlage für Assassin und Rogue.','Agile melee combat; foundation for Assassin and Rogue.']};
export default function ClassGuide({lang}:{lang:Lang}){
 const de=lang==='de',t=(a:string,b:string)=>de?a:b;
 const [data,setData]=useState<SkillData|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState('Swordsman'),[query,setQuery]=useState(''),[kind,setKind]=useState('All');
 useEffect(()=>{const c=new AbortController();setError('');api.skills(c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[refresh]);
 const classes=Object.keys(data?.skills||{});const family=data?.families.find(f=>f.erst===selected||f.zweit.includes(selected));
 const skills=useMemo(()=>(data?.skills[selected]||[]).filter(s=>(kind==='All'||s.a===kind)&&`${s.n} ${s.b||''}`.toLowerCase().includes(query.toLowerCase())),[data,selected,query,kind]);
 return <section className="helperPage classPage"><div className="helperHeading"><div><p className="panelKicker">{t('NACHSCHLAGEN & PLANEN','REFERENCE & PLANNING')}</p><h2>{t('Klassen & Skills','Classes & Skills')}</h2><p>{t('Klassenwege, Voraussetzungen und Werte je Skillstufe.','Class paths, prerequisites and values per skill level.')}</p></div><button onClick={()=>setRefresh(n=>n+1)}>{t('Aktualisieren','Refresh')}</button></div>
 <div className="helperNotice">{t('RagnaDex-Referenzdaten aus rAthena und Community. Angaben können von Zero Global abweichen. Questskills mit ungeprüftem Status sind ausdrücklich markiert. Die Effektwerte bleiben in der Quellsprache Englisch.','RagnaDex reference data from rAthena and the community. Values may differ in Zero Global. Unverified quest skills are explicitly marked. Effect values retain the source language, English.')} <a href="https://ragnadex.com/en/tools/skills/" target="_blank" rel="noreferrer">RagnaDex</a></div>
 {error&&<div role="alert" className="errorBox">{error}</div>}{!data&&!error&&<p role="status">{t('Lade Skills …','Loading skills …')}</p>}{data&&<><div className="helperFilters"><label>{t('Klasse','Class')}<select value={selected} onChange={e=>{setSelected(e.target.value);setQuery('');}}>{classes.map(c=><option key={c}>{c}</option>)}</select></label><label>{t('Skill suchen','Search skill')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{t('Art','Type')}<select value={kind} onChange={e=>setKind(e.target.value)}><option value="All">{t('Alle','All')}</option><option value="Active">{t('Aktiv','Active')}</option><option value="Passive">{t('Passiv','Passive')}</option></select></label></div>
 {family&&<div className="classPath"><h3>{family.erst} → {family.zweit.join(' / ')}</h3><p>{roles[family.erst]?.[de?0:1]}</p><div>{[family.erst,...family.zweit].filter(c=>classes.includes(c)).map(c=><button className={selected===c?'selected':''} key={c} onClick={()=>{setSelected(c);setQuery('');}}>{c}</button>)}</div></div>}
 <p aria-live="polite">{skills.length} Skills · {classes.length} {t('Klassen im Datenbestand','classes in dataset')}</p>{!skills.length&&<p>{t('Keine passenden Skills vorhanden.','No matching skills.')}</p>}
 <div className="skillGrid">{skills.map(s=><article className="skillCard" key={s.k}><h3>{s.n}</h3><p>{s.a==='Passive'?t('Passiv','Passive'):t('Aktiv','Active')} · {t('Max. Stufe','Max. level')} {s.max}</p>{s.b?<div className="skillDescription"><strong>{t('Was macht der Skill?','What does the skill do?')}</strong><p>{s.b}</p>{de&&<small>{t('Beschreibung aus der englischen Quelldatei.','Description from the English source data.')}</small>}</div>:<div className="skillDescription missing"><strong>{t('Was macht der Skill?','What does the skill do?')}</strong><p>{t('Für diesen Skill enthält die Quelle noch keine Beschreibung.','The source does not currently include a description for this skill.')}</p></div>}{s.q>0&&<p className="helperNotice">{s.q===2?t('Questskill · ungeprüft','Quest skill · unverified'):t('Questskill · laut Quelle belegt','Quest skill · evidenced by source')}</p>}<p><strong>{t('Voraussetzungen: ','Prerequisites: ')}</strong>{s.v?.length?s.v.map(([name,level])=>`${name} ${level}`).join(' · '):t('Keine laut Quelle','None listed by source')}</p><details><summary>{t('Werte je Stufe anzeigen','Show values per level')}</summary>{s.st?.length?<div className="helperTableScroll"><table><thead><tr>{Object.keys(s.st[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{s.st.map((row,i)=><tr key={i}>{Object.keys(s.st[0]).map(k=><td key={k}>{row[k]??'—'}</td>)}</tr>)}</tbody></table></div>:<p>{t('Keine Stufenwerte hinterlegt.','No per-level values listed.')}</p>}</details></article>)}</div></>}
 </section>;
}
