import { useEffect, useMemo, useState } from 'react';
import type { Lang, Monster } from './domain/types';
import { api } from './services/api-client';
import { moneyValue, spawnValue } from './domain/money';
import { MonsterPortrait } from './components/VisualIcons';
import './helpers.css';
export default function MoneyHelper({lang}: {lang:Lang}) {
 const de=lang==='de'; const t=(a:string,b:string)=>de?a:b;
 const [items,setItems]=useState<Monster[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [min,setMin]=useState(1),[max,setMax]=useState(200),[race,setRace]=useState('All'),[element,setElement]=useState('All'),[query,setQuery]=useState(''),[mode,setMode]=useState('normal');
 const [sort,setSort]=useState('spawn'),[chance,setChance]=useState(0),[cards,setCards]=useState(true),[oc,setOc]=useState(0),[completeOnly,setCompleteOnly]=useState(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');api.money(c.signal).then(d=>setItems(d.items)).catch(e=>{if(!c.signal.aborted)setError(String(e.message));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh]);
 const races=useMemo(()=>[...new Set(items.map(m=>m.race))].sort(),[items]); const elements=useMemo(()=>[...new Set(items.map(m=>m.element))].sort(),[items]);
 const ranked=useMemo(()=>items.filter(m=>{
  const variant=/^C[1-5]_/i.test(m.aegis_name)||/^(Fast|Sturdy|Wandering|Boss|Enraged)\b/i.test(m.name_en);
  return m.level>=min&&m.level<=max&&(race==='All'||m.race===race)&&(element==='All'||m.element===element)&&(mode==='all'||(mode==='variant'?variant:!variant))&&`${m.name_en} ${m.monster_id} ${(m.spawns||[]).map(s=>s.name+' '+s.code).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase());
 }).map(m=>{const value=moneyValue(m,oc,chance,cards);const spawns=(m.spawns||[]).filter(s=>!query.trim() || `${m.name_en} ${m.monster_id}`.toLowerCase().includes(query.trim().toLowerCase()) || `${s.name} ${s.code}`.toLowerCase().includes(query.trim().toLowerCase())).map(s=>({...s,value:spawnValue(value.value,s.count)})).sort((a,b)=>(b.value??-1)-(a.value??-1));return {m,...value,spawns,best:spawns[0]?.value??null};}).filter(r=>!completeOnly||r.complete).sort((a,b)=>sort==='level'?a.m.level-b.m.level:((sort==='spawn'?b.best:b.value)??-1)-((sort==='spawn'?a.best:a.value)??-1)),[items,min,max,race,element,mode,query,oc,chance,cards,completeOnly,sort]);
 const fmt=(v:number|null)=>v==null?'—':v.toLocaleString(de?'de-DE':'en-US',{maximumFractionDigits:2});
 return <section className="helperPage moneyPage"><div className="helperHeading"><div><p className="panelKicker">{t('NPC-VERKAUF • FARMING','NPC SALES • FARMING')}</p><h2>Money Helper</h2><p>{t('Vergleiche erwarteten Drop-Erlös und Monsterbestände pro Karte.','Compare expected drop revenue and monster populations per map.')}</p></div><button onClick={()=>setRefresh(v=>v+1)}>{t('Aktualisieren','Refresh')}</button></div>
 <div className="helperNotice">{t('NPC-Referenzpreise aus rAthena, nicht für Zero Global bestätigt. Erlös pro Kill = Summe aus Dropchance × NPC-Preis. Kartendurchgang = Erlös × Anzahl dieses Monsters auf einer Karte. Keine Zeitprognose und kein Gewinn nach Verbrauchskosten.','NPC reference prices from rAthena, not verified for Zero Global. Revenue per kill = sum of drop chance × NPC price. Map pass = revenue × population of this monster on one map. This is not an hourly estimate or profit after consumables.')}</div>
 <div className="helperFilters">
 <label>{t('Monster / Karte suchen','Search monster / map')}<input value={query} onChange={e=>setQuery(e.target.value)} type="search" /></label>
 <label>{t('Level von','Minimum level')}<input type="number" min="1" max="999" value={min} onChange={e=>setMin(Math.max(1,Number(e.target.value)))} /></label>
 <label>{t('Level bis','Maximum level')}<input type="number" min="1" max="999" value={max} onChange={e=>setMax(Math.max(1,Number(e.target.value)))} /></label>
 <label>{t('Rasse','Race')}<select value={race} onChange={e=>setRace(e.target.value)}><option value="All">{t('Alle','All')}</option>{races.map(r=><option key={r}>{r}</option>)}</select></label>
 <label>Element<select value={element} onChange={e=>setElement(e.target.value)}><option value="All">{t('Alle','All')}</option>{elements.map(r=><option key={r}>{r}</option>)}</select></label>
 <label>{t('Monsterart','Monster type')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="normal">{t('Normale Monster','Normal monsters')}</option><option value="variant">{t('Spezialvarianten','Special variants')}</option><option value="all">{t('Alle','All')}</option></select></label>
 <label>{t('Sortierung','Sort')}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="kill">{t('NPC-Erlös / Kill','NPC revenue / kill')}</option><option value="spawn">{t('NPC-Erlös / Kartendurchgang','NPC revenue / map pass')}</option><option value="level">{t('Niedrigstes Level','Lowest level')}</option></select></label>
 <label>{t('Mindest-Dropchance (%)','Minimum drop chance (%)')}<input type="number" min="0" max="100" step="0.1" value={chance} onChange={e=>setChance(Math.max(0,Math.min(100,Number(e.target.value))))} /></label>
 <label>{t('NPC-Verkaufsbonus (%)','NPC sale bonus (%)')}<input type="number" min="0" max="100" value={oc} onChange={e=>setOc(Math.max(0,Math.min(100,Number(e.target.value))))} /></label>
 <label className="helperCheck"><input type="checkbox" checked={cards} onChange={e=>setCards(e.target.checked)}/>{t('Karten-Drops einrechnen','Include card drops')}</label>
 <label className="helperCheck"><input type="checkbox" checked={completeOnly} onChange={e=>setCompleteOnly(e.target.checked)}/>{t('Nur vollständig berechenbare Drops','Only fully priced drops')}</label>
 </div><p className="helperMuted">{t('Filter beziehen sich auf alle geladenen Monster. Der Verkaufsbonus wird von dir vorgegeben; Spezialskills, Events und Steal sind nicht automatisch eingerechnet.','Filters apply to all loaded monsters. You supply the sale bonus; special skills, events and Steal are not included automatically.')}</p>
 {error&&<div role="alert" className="errorBox">{error}</div>}{loading?<p role="status">{t('Lade Monster und Drops …','Loading monsters and drops …')}</p>:<><p aria-live="polite">{ranked.length} {t('Monster · unbekannte Werte stehen als —','monsters · unknown values appear as —')}</p>{!ranked.length&&<p>{t('Keine Treffer. Bitte Levelbereich und Filter prüfen.','No matches. Check the level range and filters.')}</p>}<div className="moneyList">{ranked.map(r=><article className="moneyCard" key={r.m.monster_id}>
 <div className="moneySummary"><MonsterPortrait monsterId={r.m.monster_id} name={r.m.name_en} race={r.m.race} element={r.m.element}/><div><h3>{r.m.name_en}</h3><p>Lv {r.m.level} · {r.m.race} · {r.m.element} · {r.m.size}</p><small>{r.known}/{r.total} {t('Drops berechnet','drops calculated')} · {r.complete?t('Referenz','Reference'):t('Unvollständig','Incomplete')}</small></div><div><small>{t('Ø Zeny / Kill','Avg. zeny / kill')}</small><strong>{fmt(r.value)}</strong></div><div><small>{t('Ø Zeny / Kartendurchgang','Avg. zeny / map pass')}</small><strong>{fmt(r.best)}</strong></div></div>
 <details><summary>{t('Drops, Preise und Fundorte','Drops, prices and locations')}</summary><div className="helperTableScroll"><table><thead><tr><th>Item</th><th>{t('Chance','Chance')}</th><th>{t('NPC-Preis inkl. Bonus','NPC price incl. bonus')}</th><th>{t('Ø Zeny / Kill','Avg. zeny / kill')}</th></tr></thead><tbody>{r.rows.map((d,i)=><tr key={`${d.item_id}-${i}`}><td>{d.name_en} <small>#{d.item_id}</small></td><td>{fmt(d.rate_percent)}{d.rate_percent!=null?'%':''}</td><td>{fmt(d.price)}</td><td>{fmt(d.expected)}</td></tr>)}</tbody></table></div>{!r.rows.length&&<p>{t('Keine Drops für diese Auswahl.','No drops for this selection.')}</p>}<ul>{r.spawns.map(s=><li key={s.code}>{s.name} ({s.code}) · {fmt(s.count)} {t('Monster','monsters')} · {fmt(s.value)} z</li>)}</ul>{!r.spawns.length&&<p>{t('Fundort unbekannt','Location unknown')}</p>}<p className="helperMuted">{t('Teilwerte sind keine vollständige Erlösprognose. Spawnzahlen und Dropchancen bleiben Quellen-Referenzen; ein einzelner Kill garantiert keinen Drop.','Partial values are not a complete revenue estimate. Spawn counts and drop rates remain source references; a single kill does not guarantee any drop.')}</p></details></article>)}</div></>}
 </section>;
}
